Added and edited SELECT-Queries for annotation types
WDAqua/Qanary pull request #185
Opened 2023-09-22 13:00 UTC by dschiese

Added SELECT-queries for different annotation types to use in Qanary components. This way the queries stay consistent throughout the components and can be maintained from one point rather than in every single component.

2023-10-02 02:27 UTC, anbo-de commented on qanary_commons/src/main/resources/queries/select_all_AnnotationOfRelation.rq
> +<urn:qanary:output> a qa:AnnotationOfRelation .
@dschiese qanary_commons/src/main/resources/queries/select_all_AnnotationOfRelation.rq is no SELECT query. Wrong filename or wrong query?

2023-10-02 02:29 UTC, anbo-de requested changes
@dschiese qanary_commons/src/main/resources/queries/select_all_AnnotationOfRelation.rq is no SELECT query. Wrong filename or wrong query?

2023-10-04 09:44 UTC, dschiese commented
> @dschiese qanary_commons/src/main/resources/queries/select_all_AnnotationOfRelation.rq is no SELECT query. Wrong filename or wrong query?

@anbo-de Absolutely correct, fixed it with the last [commit](https://github.com/dschiese/Qanary/commit/4d6e16952ca30743b9eb45ffa7c8aaacb9818d20)

2023-10-11 00:49 UTC, anbo-de approved these changes

2023-10-11 00:49 UTC, merged